<?php
/**
 * @file ucm_commerce_downloads_config.module
 * Adds a rule that adds product key to orders when they are completed.
 */

/**
 * Implements hook_default_rules_configuration().
 */
function ucm_commerce_downloads_config_default_rules_configuration() {
  $items = array();

  $items['rules_revoke_license_on_order_delete'] = entity_import('rules_config', '{ "rules_revoke_license_on_order_delete" : {
      "LABEL" : "Revoke License and Remove Product Keys on order delete",
      "PLUGIN" : "reaction rule",
      "REQUIRES" : [ "commerce_file", "entity" ],
      "ON" : [ "commerce_order_delete" ],
      "DO" : [
        { "commerce_file_license_revoke_order" : { "order" : [ "commerce-order" ] } },
     }
      ]
    }
  }');
  return $items;
}
/**
* Implements hook_default_rules_configuration_alter
* 
* Disables rules created with other modules that issue pending licenses
* and enable other payment types.
*/
function ucm_commerce_downloads_config_default_rules_configuration_alter(&$configs) {
   //Disable a few rules
   $rulesToDisable = array('commerce_file_license_issue_checkout',
   	'commerce_checkout_order_convert',
   	'commerce_checkout_new_account',
   	'commerce_file_license_issue_checkout',
   	'commerce_payment_commerce_payment_example',
   );
   foreach($rulesToDisable as $rule) {
   	if(isset($configs[$rule])) {
   		$configs[$rule]->active = false;
   	}
   }
}
/**
*	 Implements hook_field_default_fields_alter
*  Allows the upload of any number of files per digital product and
*  allows zip tar and gz file upload extensions
*/
function ucm_commerce_downloads_config_field_default_fields_alter(&$fields) {

	$fieldName = 'commerce_product-digital_product-field_purchaseable_file';
	if(isset($fields[$fieldName])) {
		$fields[$fieldName]['field_config']['cardinality'] = FIELD_CARDINALITY_UNLIMITED;
		$fields[$fieldName]['field_instance']['settings']['file_extensions'] = 'zip tar gz';
    $fields[$fieldName]['field_instance']['widget']['settings']['filefield_sources']['filefield_sources'] = array(
      'attach' => 'attach'
    );
    $fields[$fieldName]['field_instance']['widget']['settings']['filefield_sources']['source_attach'] = array(
      'path' => 'file_attach',
      'absolute' => '0',
      'attach_mode' => 'copy',
    );
	}
  //die(var_dump($fields));
}
/**
* Implements hook_field_info_alter
* Sets the default file upload location for commerce_file to private
*/
function ucm_commerce_downloads_config_field_info_alter(&$info) {
  $fieldName = 'commerce_file';
  if(isset($info[$fieldName])) {
    $info[$fieldName]['settings']['uri_scheme'] = 'private';
  }
}
